// Generated by the command "dotnet new mfcc.coconacommand.paramset" from MFedatto
// Namespace: Mf.Evolve.Cli.Commands
// Command Name: Exec (lowercase: exec)
// ParamSet: EvolveParamSet

using Cocona;

namespace Mf.Evolve.Cli.Commands;

/// <summary>
/// Represents the exec command in the CLI.
/// </summary>
public class ExecCommand : ICommand<EvolveParamSet>
{
	/// <summary>
	/// Gets the name of the command.
	/// </summary>
	public string Name => "exec";

	/// <summary>
	/// Executes the exec command with the specified <see cref="EvolveParamSet"/>
	/// parameters.
	/// </summary>
	/// <param name="paramSet">The parameter set for the exec command.</param>
	public void Run(
		EvolveParamSet paramSet)
	{
		Console.WriteLine(paramSet.FilePath);
	}
}
