// Generated by the command "dotnet new mfcc.coconacommand.paramset" from MFedatto
// Namespace: Mf.Evolve.Cli.Commands
// Command Name: Migrate (lowercase: migrate)
// ParamSet: EvolveParamSet

namespace Mf.Evolve.Cli.Commands;

/// <summary>
/// Represents the migrate command in the CLI.
/// </summary>
public class MigrateCommand : ICommand<EvolveParamSet>
{
	/// <summary>
	/// Gets the name of the command.
	/// </summary>
	public string Name => "migrate";

	/// <summary>
	/// Executes the migrate command with the specified <see cref="EvolveParamSet"/>
	/// parameters.
	/// </summary>
	/// <param name="paramSet">The parameter set for the migrate command.</param>
	public void Run(
		EvolveParamSet paramSet)
	{
		
	}
}
