// Generated by the command "dotnet new mfcc.contextbuilder.cocona" from MFedatto
// Namespace: __namespace__
// Context: __context__

using Cocona;
using Cocona.Builder;
using __namespace__.CompositionRoot;
using __namespace__.CompositionRoot.Extensions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;

namespace __namespace__;

/// <summary>
///     Provides configuration, installation, and binding logic for the
///     __context__ entry point, implementing the 
///     <see cref="__namespace__.CompositionRoot.IContextBuilderInstaller" />, 
///     <see cref="__namespace__.CompositionRoot.IContextBuilderAppConfigurator" />,
///     and
///     <see cref="__namespace__.CompositionRoot.IContextBuilderConfigBinder" />
///     interfaces.
/// </summary>
public class __context__ContextBuilder : IContextBuilderInstaller, IContextBuilderAppConfigurator, IContextBuilderConfigBinder
{
	#region IContextBuilderConfigBinder

	/// <summary>
	///     Binds the application configuration to the specified
	///     __context__ configuration type.
	/// </summary>
	/// <param name="builder">
	///     The <see cref="CoconaAppBuilder"/> instance for configuring the
	///     application.
	/// </param>
	/// <param name="configuration">
	///     The <see cref="IConfiguration"/> instance holding the application's
	///     configuration data.
	/// </param>
	public void BindConfig(
		CoconaAppBuilder builder,
		IConfiguration configuration)
	{
		builder.BindConfig<__context__Config>(configuration);
	}

	#endregion

	#region IContextBuilderInstaller

	/// <summary>
	///     Installs the necessary services and configurations into the
	///     specified <see cref="CoconaAppBuilder" />.
	/// </summary>
	/// <param name="builder">
	///     The <see cref="CoconaAppBuilder" /> instance to configure.
	/// </param>
	/// <param name="configuration">
	///     Optional configuration settings. Defaults to <c>null</c>.
	/// </param>
	public void Install(
		CoconaAppBuilder builder,
		IConfiguration? configuration = null)
	{
		ServiceProvider serviceProvider =
			builder.Services.BuildServiceProvider();
		__context__Config __context__Config =
			serviceProvider.GetService<__context__Config>()!;
	}

	#endregion

	#region IContextBuilderAppConfigurator

	/// <summary>
	///     Configures the specified <see cref="CoconaApp" /> instance.
	/// </summary>
	/// <param name="app">
	///     The <see cref="CoconaApp" /> instance to configure.
	/// </param>
	public CoconaApp Configure(
		CoconaApp app)
	{
		if (!app.Environment.IsDevelopment())
		{
		}

		return app;
	}

	#endregion
}
